name: Generate lockfile

on:
  push:
    branches: ['hotfix/pages-deploy']

permissions:
  contents: read

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate package lock
        run: npm install --package-lock-only

      - name: Upload package lock
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json
          if-no-files-found: error
